version: '3.0'

expectations:
  population_size: 10000

actions:

  generate_cohort:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  crMAIN:
    run: stata-mp:latest analysis/cr_main.do
    needs: [generate_cohort]
    outputs:
      moderately_sensitive:
        log: logs/cr_main.log
      highly_sensitive:
        data: output/main.dta
        
  anSUMM:
    run: stata-mp:latest analysis/an_summary.do
    needs: [crMAIN]
    outputs:
      moderately_sensitive:
        log: logs/an_summary.log
        figure1: output/sgtf_perc_region.svg
        figure2: output/sgtf_perc_region.pdf
        
  anTAB1:
    run: stata-mp:latest analysis/an_table1.do
    needs: [crMAIN]
    outputs:
      moderately_sensitive:
        log: logs/an_table1.log
        table1text: output/table1.txt
        table1xlsx: output/table1.xlsx
        figure1: output/time_ae_hist.svg
        figure2: output/date_ae_hist.svg
        figure3: output/date_ae_hist1.svg
        figure4: output/ae_hist.svg
        figure5: output/ae_kden.svg

  anCOX:
    run: stata-mp:latest analysis/an_cox.do
    needs: [crMAIN]
    outputs:
      moderately_sensitive:
        log: logs/an_cox.log
        figure1: output/cox_shoen.svg
        figure2: output/cox_km.svg
        figure3: output/cox_cumhaz.svg  
        figure4: output/cox_haz.svg
        table1text: output/table2.txt
        table1xlsx: output/table2.xlsx