version: '3.0'

expectations:
  population_size: 10000

actions:

  generate_cohort:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  crMAIN:
    run: stata-mp:latest analysis/cr_main.do
    needs: [generate_cohort]
    outputs:
     moderately_sensitive:
        log: logs/cr_main.log
      highly_sensitive:
        data: output/main.dta
        
  anSUMM:
    run: stata-mp:latest analysis/an_summary.do
    needs: [crMAIN]
    outputs:
      moderately_sensitive:
        log: logs/an_summary.log
        figure1: output/sgtf_perc.svg
        figure2: output/sgtf_perc.pdf
        figure3: output/sgtf_perc_region.svg
        figure4: output/sgtf_perc_region.pdf